services:
  ftp-server:
    image: aristos86/simple-ftp-server
    build:
      context: ./
      args:
        - USER=${SYSUSER}
        - PASS=${SYSUSERPASS}
    container_name: ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - ${FTP_DIR}:/mnt/ftp
      - vsftpd-logs:/var/log/vsftpd
    restart: unless-stopped

volumes:
  vsftpd-logs:

networks:
  default:
    external: true
    name: traefik-net